### PR TITLE
add no-data wfpiconsole.ini example functionality

### PR DESCRIPTION
**Pull request by vinceskahan**
This edits config.py to give the user a chance to install an example .ini file that will bring up the dashboard with no data present at all. Edits to websockets.py are just to disable that functionality if the required variables are set UNCONFIGURED in the .ini file.

Depending on which 'variable = UNCONFIGURED' values are later filled in by the user, they can later exercise 'some' of the websockets functionality (example - if they have keys and a station id, but no CheckWX key)

I took the easy way out for copying the file into place, and did not exercise all the menus completely.  The use case here is just to get the user past the mandatory prompts of 'everything' to see 'any' of the dashboard displayed.

Apologies for any crimes against python best practices....

### CODE REVIEW

**Comment by peted-davis** [comment]
Thanks Vince - this is looking good. Just a couple of things I noticed:

1. The `Hardware` key in `wfpiconsole.ini` is critical and needs to match the system that the console is running on, or else the display can get messed up. We will need to add a check when the console is first run with the example configuration file to make sure this key is correct. This can probably be done in `lib/config.py`
2. Similar to above, we should probably make sure the version number in the example config file matches the latest version detailed in `lib/config.py`, otherwise new users will get an unnecessary popup telling them a new version is available 

Otherwise happy to merge this into the next version

**Comment by vinceskahan** [comment]
Sure.   Would it be appropriate to overwrite those two items after copying the example .ini into place after line 91 or so in the modified config.py where it says:

                shutil.copy('wfpiconsole.ini.example','wfpiconsole.ini')
                print('Copied')

???

**Comment by vinceskahan** [comment]
done - checks out ok here for me

**Comment by peted-davis** [comment]
This looks good. I should get a chance to review over the weekend. Thanks again!

**Comment by vinceskahan** [comment]
Just a fyi - the PR as it stands today 'does' work fine for the primary use case of '**_install the console before my Tempest arrives in the mail'_**, but if you later go in after the fact and enable certain things in the .ini file manually, your watchdog timers will eventually kick in and throw errors which are just annoyances fortunately.

As a nice-to-have what I'd like to be able to do long-term is to run with UDP for the data source yet still be able to hit WF for the forecast panel (for example).

There have to be places I missed re: watchdogs in your async stuff, and I'm wondering if some feature flag ala 'disable sensor watchdog' or the like might be a better way than looking for lack of a configured StationID or sensor ID in the .ini file.

I also noticed you seem to overwrite the .ini file under the hood so I was reluctant to go in and add options to the .ini file without asking first.

(that said - this PR works fine as-is for the primary use case, I can do others if you want to go down a feature flag path...)

**Comment by peted-davis** [comment]
Can you give an example of what items need to be specified in the .ini file to trigger the watchdogs? I'd rather handle this without a .ini file entry. I'm sure some 'tinkerer' will switch them off when they are required, causing support headaches when the websocket falls offline

**Comment by vinceskahan** [comment]
Sure. I found that if you define a TempestID the async code will look for obs_st and eventually the watchdog tries to reset things with no obs_st is found for enough minutes.   That's of course its reason to exist.  You normally 'want' the watchdog to trip in the normal case.   It's a feature, not a bug.

But for 'this' use case, the original PR that I submitted didn't hold up well in testing my growing UDP-based setup, which sometimes 'wants' to define which sensor(s) to pick UDP data from.  I couldn't key off lack of a TempestID  to disable the watchdogs, yet I needed a Tempest ID for my customPanels.

So I went back to the feature flag idea.

The reason I like the .ini feature flag for my use cases is simplicity in the code and for the user...

- It lets me set one one variable True to switch to 'websockets disabled'
- Yet the console can still do most of the other things the console and WF support:
    - ex: you can still get forecasts from WF if certain things are valid in the .ini file
- And having one variable to set True makes it simple to later go back to websockets and (perhaps) still use whatever customPanels are in place

So simpler for support, simple for the user to turn on/off, yet it still leverages most of the PiConsole heavy lifting that happens under the hood.  Pretty nice.

**Comment by peted-davis** [comment]
Gotcha! That makes complete sense. I hadn't linked in my mind the requirement for the feature flag and your UDP work. I will get on and review this PR (assuming I can't find the time away from the family 🤣)

**Comment by vinceskahan** [comment]
There is no rush at all, and family always wins !!!!

I'm walking away from the UDP thing for a while, as I got lost under the hood in your code trying to bolt things into it, but I might go back to it eventually.  Regardless, this PR is helpful for the more common use case where folks want to spin up a console and get their pi set up while they're waiting for their gear to arrive in the mail or the like.

(example - if you turn websockets off yet define a systemid and wf key, forecast panel works :-)

**Comment by vinceskahan** [comment]
Pete - now that you're making a lot of progress with the UDP variant (cool!) can you revisit this PR when you get a chance please ?  If you need help with the merge conflicts that popped up since you tweaked this one let month, let me know.

**Comment by vinceskahan** [comment]
Looks like you had a bit of a git merge massacre as well as a little ripple from your separate addition of UDP support and being able to turn off rest_api...

For a procedure, I did a clean reimaging and ran the curl script, then did a "wfpiconsole install" and then a "beta" and then the initial "start" and got the new queries.  Then things went a bit boom...

- queryUser() somehow is missing from lib/config.py - added it back in from the main branch
- needed to change 'Hardware' to 'hardware' around line 100 in lib/config.py
- needed to add rest_api = 0 to the .example file
- needed to add a bogus StationID = 12345 to the .example file
- needed to add either "Connection = Websocket"  to the .example file

Re: conflicts with the UDP stuff you might want to also want to template out bogus values for the various SN fields into the .example file too so that switching from demo to udp is seamless.  I set them to match my simulator for now with just a Tempest defined:

- TempestSN = ST-00000001
- SkySN =
- InAirSN =
- OutAirSN =

**Pull request merged**
